### ISSUE TITLE
Unable to use with latest nix (Jan 2019)

### ISSUE THREAD

**Issue by swamp-agr** [phadej/insert-ordered-containers#28] opened 2019-01-21 10:08 UTC
Hi @phadej, I wanted to use `swagger2` with `nix` and wasn't able to achieve the goal with error: 

```
Configuring insert-ordered-containers-0.2.1.0...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:950:20 in Cabal-2.4.0.1:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:460:12 in Cabal-2.4.0.1:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.4.0.1:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.4.0.1:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.4.0.1:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.4.0.1:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing dependencies:
tasty >=0.10.1.2 && <1.2

builder for '/nix/store/yfwz0vml7y6cvcml7ym5s2w7zvacwv5z-insert-ordered-containers-0.2.1.0.drv' failed with exit code 1
cannot build derivation '/nix/store/hp57s6syjfbmj0yi1fblv94z4zgclq7l-ghc-8.6.3-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/hp57s6syjfbmj0yi1fblv94z4zgclq7l-ghc-8.6.3-with-packages.drv' failed
```

I navigated through `hackage` to https://hydra.nixos.org/job/nixpkgs/trunk/haskellPackages.insert-ordered-containers.x86_64-linux and noticed the same error: https://hydra.nixos.org/build/86432701/nixlog/2

Since I am not familiar with `nix`, I don't know yet the flow about how to fix this issue on `nix` side so I am asking you here.
Could you please suggest next steps to resolve this issue on `nix` side?

Thanks,
@swamp-agr

**Comment by phadej** [comment] 2019-01-21 10:16
Duplicate of https://github.com/phadej/insert-ordered-containers/issues/27

Unfortunately I'm not an nix(pkgs) user myself. You should ask `nixpkgs` maintainers.

**Closed by phadej** 2019-01-21 10:16 UTC

**Comment by swamp-agr** [comment] 2019-01-21 10:23
Ok, @phadej, thanks for suggestion. I will try to make it.
